### ISSUE TITLE
Octopus erste Auffälligkeiten

### ISSUE THREAD

**Issue by OXERY** [Prutsium/3D-Druckerplausch-Klipper#1]
Hier die ersten Auffälligkeiten beim Test des Octopus Boards in Zusammenhang mit der Universal Config
- [ ] "neue" Mesh-Methode deaktivieren
- [ ] probe speed von 1.0 auf 5.0 stellen
- [ ] probe samples auf 5 erhöhen (wie früher?)
- [ ] (oder bei samples_result: average stattdessen auf median? Falls eine Messung falsch ist)
- [ ] Bei Filament-Unload wird der Display-Text hinterher nicht auf "leer" zurückgesetzt

**Comment by OXERY** [comment]
- [ ] Nach PID-Tuning (egal ob Bed oder Extruder) kann man die Parameter mit save_config nicht speichern ("!! SAVE_CONFIG section 'extruder' option 'control' conflicts with included value")
- [ ] Änderung der Neopixel-Farbe von Display und Button speicherbar machen

**Comment by OXERY** [comment]
Beim Aktivieren der pi adxl cfg kommt nach Neustart "Unknown spi_bus 'spi3'" (in der octopus.cfg steht auch ein adxl drin, daher)

**Comment by OXERY** [comment]
Als Idee noch: keine printer.cfg mehr ausliefern, sondern printer_example.cfg und "printer.cfg" in die .gitignore. Dann könnte man auf dem Fluiddpi ein `git pull` machen und müsste sich keine Sorgen um seine printer.cfg machen

**Comment by Prutsium** [comment]
All issues have been resolved in Universal Config Revised
