### ISSUE TITLE
Einsy pins.cfg

### ISSUE THREAD

**Issue by sdooweloc** [Prutsium/3D-Druckerplausch-Klipper#2]
In the pins.cfg for Boards/Einsy/pins.cfg there is a stray comma that causes compile errors as seen below between x_uart_pin and x_tx_pin's entries.

Also this is labeled as octopus_11_tmc2209 instead of something more einsy related like einsy_2130?

https://github.com/Prutsium/3D-Druckerplausch-Klipper/blob/8950a571f9cff511c0ee520111bf97c7c5b77ea3/Klipper_cfg/Prusa_Universal_Config_Revised/Boards/Einsy/pins.cfg#L6-L9

**Comment by Prutsium** [comment]
Both are fixed thanks for the heads-up.
Also i have disabled the plot_graph menu sections by default so it wont error out.
When you want to use it you need the patch from KIAUH for example to execute shell commands

**Comment by sdooweloc** [comment]
Perfect thank you!
